language: R
sudo: false

r:
  - oldrel
  - release
  - devel

before_install:
  - Rscript -e "source('https://wush978.github.io/R/repos_as_release.R')"

script:
  - R CMD build .
  - ls -d1 swirl*tar.gz | xargs R CMD check 
  - ls -d1 swirl*tar.gz | xargs R CMD INSTALL
  - git clone https://github.com/wush978/DataScienceAndR.git -b course /tmp/course
  - cd /tmp/course && (echo "source('https://raw.githubusercontent.com/wush978/R/gh-pages/.test_course.R')" | R --no-save --args push)

addons:
  apt:
    packages:
    - libssl-dev
    - libcurl4-openssl-dev
    - libxml2-dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8552957f2dea4217e0ed
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

  
